name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_NPM_AUTH_TOKEN }}" > ~/.npmrc
          echo "@chordcommerce:registry=https://npm.pkg.github.com" >> ~/.npmrc
          yarn install --frozen-lockfile
      - name: Lint
        run: |
          yarn lint
      - name: Prettier
        run: |
          yarn prettier:check
      - name: Build @chordcommerce/analytics
        run: |
          cd packages/analytics && yarn build
      - name: Test @chordcommerce/analytics
        run: |
          cd packages/analytics && yarn test:ci
